Update kubectl to 1.25.4
rancher/shell pull request #104
Opened 2022-11-23 09:37 UTC by TomyLobo

1.21 exceeds the allowed skew for modern kubernetes versions

2022-11-29 12:38 UTC, macedogm commented
@TomyLobo can you please update the PR to use `v1.23` instead? K8s `v1.25` is not supported in Rancher yet, so Kubectl in `v1.23` can communicate with `v1.22`, `v1.23` and `v1.24` clusters.

2022-11-29 18:36 UTC, TomyLobo commented
> @TomyLobo can you please update the PR to use `v1.23` instead? K8s `v1.25` is not supported in Rancher yet, so Kubectl in `v1.23` can communicate with `v1.22`, `v1.23` and `v1.24` clusters.

done.
Rancher should really be modified to use a kubectl version that fits the cluster instead of trying to make one size fit all cluster.

2022-11-29 18:37 UTC, TomyLobo commented
Resolved conflicts

2022-11-29 18:43 UTC, TomyLobo commented
force-pushed a single commit to make less of a mess

2022-12-02 14:47 UTC, TomyLobo commented
so when does this get merged, built and tagged?
also, would I need to update rancher to make the new tag the default?

2023-01-10 12:25 UTC, crobby approved these changes

2023-01-10 13:03 UTC, macedogm requested changes

2023-01-10 13:03 UTC, macedogm commented on package/Dockerfile
> +ENV KUBECTL_VERSION v1.23.14
@TomyLobo can you please bump to [v1.24.9](https://github.com/kubernetes/kubectl/releases/tag/v0.24.9) and then we can merge it, please?

```suggestion
ENV KUBECTL_VERSION v1.24.9
```

2023-03-08 18:56 UTC, macedogm commented
@TomyLobo we are closing this in favor of https://github.com/rancher/shell/pull/164. Thank you for your support with this.

2023-03-08 18:56 UTC, closed without merging